<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 *
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var $block \MSP\Iubenda\Block\Iubenda
 */
?>

<?php if ($block->exist()) : ?>
    <!-- MSP Iubenda -->
    <div id="iubenda-container" data-mage-init='{ "msp_iubenda": {
        "policyId" : <?php echo $block->getPolicyId() ?>
    } }'>
        <div class="content">
            <span class="close">X</span>
            <p><?php echo __('Informativa') ?></p>
            <p>
                <?php echo $block->getTextBeforeLink() ?>
                <a href="//www.iubenda.com/privacy-policy/<?php echo $block->getPolicyId() ?>"
                   target="_blank"
                   class="iubenda-black no-brand iubenda-embed"
                   title="Privacy Policy"><?php echo $block->getTextLink() ?></a>
                .<br/>
                <?php echo $block->getTextAfterLink() ?>
            </p>
        </div>
    </div>
    <!-- _MSP Iubenda -->
<?php endif; ?>